### ISSUE TITLE
[root] Swagger 설정 실수로 삭제되서 생긴 오류

### ISSUE THREAD

**Issue by gdtknight** [FastCampus-Mini5/BE_server#74]
```yml
  mvc:
    path match:
      matching-strategy: ant_path_matcher
```
